### ISSUE TITLE
auto installer.... requires keyboard input?

### ISSUE THREAD

**Issue by sumoyoshikai** [netson/ubuntu-unattended#24]
Ok, I figured this was what I needed to automatically get me up and running. The problem was, the image built just fine (the download links all fail of course, ubuntu has moved folder locations) but it made the unattended iso no problems. it boots the unattended iso no problems.

why on earth is an UNATTENDED iso booting to a menu where you are required to select from the options:

Autoinstall NETSON Ubuntu Server
Install Ubuntu Server
Multiple Server install with MAAS
Check disc for defects
Test Memory
Boot from first hard disk
Rescue a broken disc

and of course it just hangs there. It does nothing. How is this unattended? if anything, this would be ATTENDED?

**Comment by dgleba** [comment]
Somebody Please correct me if I am wrong here.

I believe it is stopping at that point because without that, if you accidentally boot the image in a machine you don't want to destroy, it will just wipe the system and data on that computer out and install this. Quite dangerous.

I wanted it to just do that from my scripts for automatic VM creation. I changed it to this:

https://github.com/dgleba/vamp206a/blob/master/05create-unattended-iso.sh#L180

My copy is outdated, so keep that in mind.
