### ISSUE TITLE
Create script gets stuck

### ISSUE THREAD

**Issue by gtarik** [netson/ubuntu-unattended#57]
Hey guys, 
I tried to generate a new iso file with ur create-unattended-iso.sh script.
It doesnt even get to show the available versions of ubuntu, it should show 20.04 as the newest version.

Has anyone tested/used it recently? Have u to modify anything before starting the script?
Thanks in advance

**Comment by lmckiwo** [comment]
I just executed it., and it seems to work for me:

$ sudo ./create-unattended-iso.sh

 +---------------------------------------------------+
 |            UNATTENDED UBUNTU ISO MAKER            |
 +---------------------------------------------------+

./create-unattended-iso.sh: line 63: lsb_release: command not found
Building menu from available builds
Ubuntu 12.04.5 LTS (Precise Pangolin)
Ubuntu 14.04.6 LTS (Trusty Tahr)
Ubuntu 16.04.6 LTS (Xenial Xerus)
Ubuntu 18.04.4 LTS (Bionic Beaver)
Ubuntu 19.10 (Eoan Ermine)
Ubuntu 20.04 LTS (Focal Fossa)

 which ubuntu edition would you like to remaster:

 [1] Ubuntu 12.04.5 ("Precise Pangolin")
 [2] Ubuntu 14.04.1 ("Trusty Tahr")
 [3] Ubuntu 14.04.2 ("Trusty Tahr")
 [4] Ubuntu 14.04.3 ("Trusty Tahr")
 [5] Ubuntu 14.04.4 ("Trusty Tahr")
 [6] Ubuntu 14.04.5 ("Trusty Tahr")
 [7] Ubuntu 14.04 ("Trusty Tahr")
 [8] Ubuntu 14.04.6 ("Trusty Tahr")
 [9] Ubuntu 16.04.1 ("Xenial Xerus")
 [10] Ubuntu 16.04.2 ("Xenial Xerus")
 [11] Ubuntu 16.04.3 ("Xenial Xerus")
 [12] Ubuntu 16.04.4 ("Xenial Xerus")
 [13] Ubuntu 16.04.5 ("Xenial Xerus")
 [14] Ubuntu 16.04 ("Xenial Xerus")
 [15] Ubuntu 16.04.6 ("Xenial Xerus")
 [16] Ubuntu 18.04.4 ("Bionic Beaver")
 [17] Ubuntu 19.10 ("Eoan Ermine")

 please enter your preference: [1-17]:


The reason why you don't see version 20 is because there is no server iso  (not the server-live) iso.

**Comment by gtarik** [comment]
Hm okay. So it should work out of the box?
The thing is I dont get to see any version listed, not only the 20.04 server.
Is there any way to make it a offline conversion? Without any listing/downloading, since I already know which .iso image I want to convert.
Thanks

**Comment by lmckiwo** [comment]
what platform are you running the script on? Are there any error messages?  Can you show me a screen snapshot of the output?

I am curious why it is not working for you because this should work out of the box.

As for running the conversion offline, I don't have the procedure to do it, but what I do know is that it does not work with any iso.  I had tested with server-live iso, and that does not work.

But there are manual steps out there if you can find.  Here is one i found to create unattended for desktop version 16, but it should be similiar for other versions.  [https://ernestas.me/2017/02/12/ubuntu-16.04-desktop-unattended-installation](url)

**Comment by deviantdev** [comment]
> Hey guys,
> I tried to generate a new iso file with ur create-unattended-iso.sh script.
> It doesnt even get to show the available versions of ubuntu, it should show 20.04 as the newest version.
> 
> Has anyone tested/used it recently? Have u to modify anything before starting the script?
> Thanks in advance

yeh, this problem. U can repair it -> https://github.com/netson/ubuntu-unattended/issues/59

ubuntu-unattended/create-unattended-iso.sh
`for version in $(wget -qO - http://cdimage.ubuntu.com/releases/ | grep -w DIR | grep -oP href=\"[0-9].* | cut -d'"' -f2 | tr -d '/'); do`
replace
`for version in $(wget -qO - http://cdimage.ubuntu.com/releases/ | grep -oP href=\"[0-9].* | cut -d'"' -f2 | tr -d '/'); do`

**Comment by lmckiwo** [comment]
Fixed. Please close issue.
